# Generated by Django 2.2.1 on 2019-05-09 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('locale', models.CharField(choices=[('en', 'English'), ('ko', 'Korean'), ('ja', 'Japanese')], max_length=2)),
                ('value', models.TextField()),
                ('key_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.Key')),
            ],
        ),
    ]
