# Generated by Django 2.2.1 on 2019-05-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='key_id',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='key',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('key', 'locale')},
        ),
    ]
